### PR TITLE
Bring sjrmui to the next level

### PR DESCRIPTION
**Pull request by t-h-a-l-i-s**
* lifted the versions of everything (Scala, SBT, SBT Plugins, Webpack,
  ...) to stable HEAD state
* adjusted the wrapper classes to Work with scalajs-react
* applied a scalafmt to have a consistent format (just a first format
  setting - can be adjusted to the format of ScalaJS if wished)
* adjusted the Webpack DevServer configuration to automatically open
  the index-dev.html file

### CODE REVIEW

**Comment by t-h-a-l-i-s** [comment]
Hmm. I guess this project seems to be dead.

**Comment by zalbia** [comment]
Hi @t-h-a-l-i-s, we've just been really swamped with work these days. Let me get back to you in a week or so and I will check your PR. Hell, I'll give you the reins on this project since you've already put a tremendous amount of work into it.

**Comment by zalbia** [comment]
@t-h-a-l-i-s, looking at it right now.

**Comment by zalbia** [comment]
@t-h-a-l-i-s Thanks for your hard work. Will include you in the list of contributors. I'm sending you an [invite](https://github.com/pangwarta/scalajs-react-material-ui/invitations) to be an admin on this project.

**Comment by t-h-a-l-i-s** [comment]
thanks, zachary. I have a few improvements I can contribute.

**Pull request merged**
